version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dashboard_network
  
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: rixen1221/webstore_back:latest
    ports:
      - "5001:8080"
    depends_on:
      - postgres
    volumes:
      - ./wwwroot/images:/app/wwwroot/images
      - ./wwwroot/templates:/app/wwwroot/templates
      - ./:/source
    environment:
      ConnectionStrings__PostgresDocker: "Server=postgres;Port=5432;Database=postgres;User Id=postgres;Password=postgres;"
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - dashboard_network

networks:
  dashboard_network:
    driver: bridge

volumes:
  postgres_data: